sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t adn888/docker-react -f Dockerfile.dev . 

script:
    - - docker run -e CI=true adn888/docker-react npm run test