sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t adn888/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true test_image npm run test -- --coverage